name: tests

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  release:
    types:
      - edited
      - released

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v5
    - name: Linting
      run: |
        make lint

    - name: Static Testing
      run: |
        make static

    - name: Run unit tests
      run: |
        make unit